name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Dependencies
        run: npm ci

      - name: Lint and Test
        run: npm test

      - name: Build
        run: npm run build

      - if: github.ref == 'refs/heads/master'
        name: Deploy
        run: echo $CLASPRC > ~/.clasprc.json && npm run deploy
        env:
          CLASPRC: ${{ secrets.CLASPRC }}
